### PR TITLE
Support itkv5 and python3

### PR DESCRIPTION
**Pull request by jcfr**
This PR updates the code base to build against ITKv5 and support python3.

Note that the self test is still failing, there are differences in the data generated at each steps. For the first 4 steps, the difference is not significant and the computed signature could be updated. That said it would be nice to understand the origin of the difference.

But for the remaining of the steps, there are problem to be addressed. To help with this.

You will find below:
* a script that can be copied into the python interactor in both the latest Stable release (4.10) and the latest nightly (4.11). It saves the segmentation at each step along with the segmentation stats.
* a scene with segmentation of each steps loaded and overlaid, it allows to see if differences are significant or not.

### Script

```python
import os
import tempfile
from SegmentStatistics import SegmentStatisticsLogic

# global variables
version="%s.%s" % (slicer.app.majorVersion, slicer.app.minorVersion)
data_dir=os.path.join(tempfile.gettempdir(), "PETTumorSegmentation-Comparison", version)
labelmap = None

# load data
slicer.util.selectModule(slicer.modules.segmenteditorpettumorsegmentationeffectselftest)
slicer.modules.SegmentEditorPETTumorSegmentationEffectSelfTestWidget.onLoadTestData()

def getSignature():
  global labelmap
  if labelmap is None:
    labelmap = slicer.vtkMRMLLabelMapVolumeNode()
    slicer.mrmlScene.AddNode(labelmap)
  slicer.modules.segmentations.logic().ExportAllSegmentsToLabelmapNode(seg, labelmap)
  stat = vtk.vtkImageAccumulate()
  stat.SetInputData(labelmap.GetImageData())
  stat.Update()
  return int(round(stat.GetMean()[0]*1e10))

def saveResults(stepName):
  
  if not os.path.exists(data_dir):
    os.makedirs(data_dir)
  
  # save segment
  slicer.util.saveNode(seg, os.path.join(data_dir, "%s-%s.seg.nrrd" % (stepName, version)))
  
  # compute and save stats 
  segStatLogic = SegmentStatisticsLogic()
  parameterNode = segStatLogic.getParameterNode()
  parameterNode.SetParameter("Segmentation", seg.GetID())
  parameterNode.SetParameter("ScalarVolume", petNode.GetID())
  parameterNode.SetParameter('visibleSegmentsOnly', str(False))
  segStatLogic.computeStatistics()
  
  resultsTableNode = slicer.vtkMRMLTableNode()
  slicer.mrmlScene.AddNode(resultsTableNode)
  segStatLogic.exportToTable(resultsTableNode)
  
  slicer.util.saveNode(resultsTableNode, os.path.join(data_dir, "%s-%s.csv" % (stepName, version)))

slicer.util.delayDisplay('Loading PET DICOM dataset (including download if necessary)')
petNode = getNode("vtkMRMLScalarVolumeNode1")
slicer.util.delayDisplay('Switching to Segment Editor')
slicer.util.mainWindow().moduleSelector().selectModule('SegmentEditor')
widget = slicer.modules.SegmentEditorWidget
editor = widget.editor
params = widget.parameterSetNode
seg = widget.editor.segmentationNode()

editor.saveStateForUndo()
addedSegmentID = seg.GetSegmentation().AddEmptySegment()
editor.setCurrentSegmentID(addedSegmentID)

slicer.util.delayDisplay('Activating PET Tumor Segmentation effect')
editor.setActiveEffectByName('PET Tumor Segmentation')
effect = editor.activeEffect()

# step1: one-click segmentation
slicer.util.delayDisplay('Applying ne-click segmentation')
effect.self().onApplyMouseClick([41.3,220.1,-980.2])
saveResults("step1")
# self.assertEqual(self.getSignature(seg),2893772894)

# step2: global refinement
slicer.util.delayDisplay('Applying global refinement')
effect.self().globalRefinementRadioButton.click()
effect.self().onApplyMouseClick([40.1,264.2,-969.2])
saveResults("step2")
# self.assertEqual(self.getSignature(seg),3700505133)

# step3: local refinement
slicer.util.delayDisplay('Applying local refinement')
effect.self().localRefinementRadioButton.click()
effect.self().onApplyMouseClick([40.1,258.1,-1025.1])
saveResults("step3")
# self.assertEqual(self.getSignature(seg),3550788737)

# step4: undo with local refinement
slicer.util.delayDisplay('Testing undo with local refinement')
editor.undo()
saveResults("step4")
# self.assertEqual(self.getSignature(seg),3700505133)

effect.self().onApplyMouseClick([40.1,234.2, 934.7])

# step5: go back to initial segmentation before refinement and use splitting option
slicer.util.delayDisplay('Applying splitting option')
editor.undo()
editor.undo()
effect.self().splittingCheckBox.checked = True
effect.self().onApplyParameters()
saveResults("step5")
# self.assertEqual(self.getSignature(seg),4231292517)

# add second segment
slicer.util.delayDisplay('Adding second segment')
editor.saveStateForUndo()
addedSegmentID = seg.GetSegmentation().AddEmptySegment()
editor.setCurrentSegmentID(addedSegmentID)

# step6: one-click segmentation
slicer.util.delayDisplay('Applying one-click segmentation')
effect.self().onApplyMouseClick([41.3,229.1,-952.5])
effect.self().onApplyParameters()
saveResults("step6")
# self.assertEqual(self.getSignature(seg),4226190476)

# step7: assist centering
slicer.util.delayDisplay('Applying assist centering option')
effect.self().assistCenteringCheckBox.checked = False
effect.self().onApplyParameters()
saveResults("step7")
# self.assertEqual(self.getSignature(seg),4401777778)

# step8: sealing centering
slicer.util.delayDisplay('Applying sealing option')
effect.self().sealingCheckBox.checked = True
effect.self().onApplyParameters()
saveResults("step8")
# self.assertEqual(self.getSignature(seg),4451555556)

# step9: overwriting
slicer.util.delayDisplay('Applying overwriting option')
effect.self().allowOverwritingCheckBox.checked = True
effect.self().onApplyParameters()
saveResults("step9")
# self.assertEqual(self.getSignature(seg),5756378601)

# step10: undo
editor.undo()
saveResults("step10")
# self.assertEqual(self.getSignature(seg),4451555556)

```

### Segmentation at each steps for both 4.10 and 4.11

* green, yellow: Slicer 4.10
* red, purple: Slicer 4.11

image

* Scene: Download and renamed to `2019-04-18-Scene.mrb` before loading:
[2019-04-18-Scene.mrb.zip](https://github.com/QIICR/PETTumorSegmentation/files/3095186/2019-04-18-Scene.mrb.zip)

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @fedorov

**Comment by chribaue** [comment]
Thank you @jcfr! Your work will certainly help a lot with the transition! I'll look into it in more detail, also as to why there are differences in the output, as soon as I find time.

**Comment by jamesobutler** [comment]
@chribaue Did this work ultimately get integrated into the `master` branch as https://github.com/QIICR/PETTumorSegmentation/commit/04237c7a4196cd4b14a687c3b977dd50c7ce9875? Does this PR need to remain open?

**Comment by chribaue** [comment]
We can close this PR. I've integrated the changes related to itk5 and python3 and fixed the remaining issues.

**Comment by jcfr** [comment]
Thanks for the follow up and it is great that similar changes have been integrated :100: 

> also as to why there are differences in the output,

@chribaue  Did you also have a chance to investigate the issue I originally discussed with this pull request (see above for screenshot and script)

**Comment by chribaue** [comment]
@jcfr Thank you for all your input!

>> also as to why there are differences in the output,

The differences had nothing to do with the tumor segmentation algorithm. 
The back-ends in Slicer for loading the DICOM volumes had changed and they read the image spacing and origin information with different precision. This caused a slight shift of the structures relative to the user "clicks".

Manually setting spacing and and origin after loading the volumes solved the problem:
https://github.com/QIICR/PETTumorSegmentation/blob/master/Testing/SegmentEditorPETTumorSegmentationEffectSelfTest.py#L124-L125

**Pull request closed without merging**
